version: '3.8'

services:
  # Vue.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    # For development with hot-reload (comment out the build section above when using this)
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # command: npm run dev
